metricbeat.config.modules:
  path: conf/*.yml
  reload.enabled: true

processors:
  - add_locale: ~

output.logstash:
  hosts: ["${BLUECATS_HOST:?환경변수 값으로 BLUECATS_HOST값을 127.0.0.1:7700 과 같은 형태로 추가하세요.}"]