metricbeat.config.modules:
  path: conf/*.yml
  reload.enabled: true

output.logstash:
  hosts: ["${BLUECATS_HOST:?환경변수 값으로 BLUECATS_HOST값을 127.0.0.1:7700 과 같은 형태로 추가하세요.}"]

processors:
  - add_locale: ~
  - add_fields:
      fields_under_root: true
      fields:
        KAFKATOPIC: metricbeat
        BEATNAME: metricbeat-VERSION_INFO_HERE
        DMS50: ${BLUECATS_DMS50:false}
        VERSION: VERSION_INFO_HERE


